services:
- type: pserv
  name: minio
  env: docker
  plan: standard
  disk:
    name: miniodata
    mountPath: /data
    sizeGB: 10
  autoDeploy: false
  envVars:
    - key: MINIO_ACCESS_KEY
      value: admin
    - key: MINIO_SECRET_KEY
      value: password

